spring.application.name=Tinder-API-Gateway
# JWT Configuration
# ===============================
secret.key=${JWT_SECRET_KEY}

app.jwt.login-redirect-url=${LOGIN_URL}

eureka.client.service-url.defaultZone=http://tinder-service-registry:8761/eureka/
eureka.client.fetch-registry=true
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.webflux.routes[0].id=user-service
spring.cloud.gateway.webflux.routes[0].uri=lb://user-service
spring.cloud.gateway.webflux.routes[0].predicates[0]=Path=/user-service/**
spring.cloud.gateway.webflux.routes[0].filters[0]=StripPrefix=1

# Orchestration Service route
spring.cloud.gateway.webflux.routes[1].id=orchestration-service
spring.cloud.gateway.webflux.routes[1].uri=lb://orchestration-service
spring.cloud.gateway.webflux.routes[1].predicates[0]=Path=/orchestration/**
# ✅ ADD THIS
spring.cloud.gateway.webflux.routes[1].filters[0]=StripPrefix=1

