spring.application.name=user-service

# Database configuration

# spring.datasource.url=jdbc:mysql://mysql:3306/tinder_user_service
spring.datasource.url=jdbc:mysql://tinder-user-service-mysql:3306/tinder_user_service
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# JWT Configuration
# ===============================
secret.key=${JWT_SECRET_KEY}

spring.kafka.bootstrap-servers=Tinder-kafka:9092

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://tinder-service-registry:8761/eureka/
# ===============================
# HikariCP Configuration
# ===============================
spring.datasource.hikari.maximum-pool-size=28
spring.datasource.hikari.minimum-idle=10
# spring.datasource.hikari.connection-timeout=5000
