services:
  mysql:
    volumes:
      - ./login-seed.sql:/docker-entrypoint-initdb.d/login-seed.sql
    networks:
      - tinder-test-network

  user-service:
    networks:
      - tinder-test-network

networks:
  tinder-test-network:
    external: true
