spring.application.name=Pairing-Service
eureka.client.service-url.defaultZone=http://tinder-service-registry:8761/eureka/
server.port=8092
spring.kafka.consumer.group-id=pairing-group
app.kafka.topics.pairing-topic=pairing-events